CREATE TABLE IF NOT EXISTS ToDo (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TARGET_DATE DATE,
    DONE BOOLEAN
);

INSERT INTO ToDo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (1, 'Adnan1', 'Learn Spring', '2020-01-01', 'false');
INSERT INTO ToDo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (2, 'Adnan1', 'Learn Spring MVC', '2020-01-01', 'false');
INSERT INTO ToDo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (3, 'Adnan2', 'Learn to Dance', '2020-01-01', 'false');
INSERT INTO ToDo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (4, 'Adnan2', 'Learn to Rock', '2020-01-01', 'false');